#server:
#  port: 8021
#  
#spring:
#  application: 
#    name: edu-ems
#  cloud:
#    nacos:
#      server-addr: 127.0.0.1:8848     
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/yxz_edu_ems?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
#    username: root
#    password: 123456
#  http:
#    encoding:
#      charset: UTF-8
#      force: true
#      enabled: true  
#  thymeleaf:
#    cache: false     
#  resources:
#    static-locations: classpath:/   
##      
##  
##mybatis-plus:
##  global-config:
##    db-config:
##      id-type: auto
##  mapper-locations: classpath:/mapper/**/*.xml
##    
##
##management:
##  endpoints:
##    web:
##      exposure:
##        include: "*"    
