/*
SQLyog Community v12.09 (64 bit)
MySQL - 5.7.20-log 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

insert into `tms_teacher` (`id`, `institution_id`, `name`, `gender`, `birth`, `mobile`, `email`, `post_id`, `hired`, `leaved`, `is_leaved`, `note`, `token`, `is_actived`, `logic_deleted`, `created`, `updated`, `user_id`) values('1','1','Neal','1','1970-01-04','0481982299','yu_xinzhong@163.com',NULL,'2021-03-10 00:00:00','2039-11-23 13:00:00','0','good teacher',NULL,'1',NULL,NULL,NULL,NULL);
insert into `tms_teacher` (`id`, `institution_id`, `name`, `gender`, `birth`, `mobile`, `email`, `post_id`, `hired`, `leaved`, `is_leaved`, `note`, `token`, `is_actived`, `logic_deleted`, `created`, `updated`, `user_id`) values('2','1','John','1','1974-12-05','0481982299','yu_xinzhong@163.com',NULL,'2021-02-28 13:00:00','2049-11-24 13:00:00','0','',NULL,'0',NULL,NULL,NULL,NULL);
insert into `tms_teacher` (`id`, `institution_id`, `name`, `gender`, `birth`, `mobile`, `email`, `post_id`, `hired`, `leaved`, `is_leaved`, `note`, `token`, `is_actived`, `logic_deleted`, `created`, `updated`, `user_id`) values('3','1','Mary','2',NULL,'','yxz20180810@gmail.com',NULL,'2021-02-28 13:00:00','2021-02-28 13:00:00','0','',NULL,'1',NULL,NULL,NULL,NULL);
insert into `tms_teacher` (`id`, `institution_id`, `name`, `gender`, `birth`, `mobile`, `email`, `post_id`, `hired`, `leaved`, `is_leaved`, `note`, `token`, `is_actived`, `logic_deleted`, `created`, `updated`, `user_id`) values('4','1','Alice','2',NULL,'','yxz20180810@gmail.com',NULL,'2021-02-28 13:00:00','2021-02-28 13:00:00','0','',NULL,'0',NULL,NULL,NULL,NULL);
insert into `tms_teacher` (`id`, `institution_id`, `name`, `gender`, `birth`, `mobile`, `email`, `post_id`, `hired`, `leaved`, `is_leaved`, `note`, `token`, `is_actived`, `logic_deleted`, `created`, `updated`, `user_id`) values('5','1','Amy','2',NULL,'','yxz20180810@gmail.com',NULL,'2021-02-28 13:00:00','2021-02-28 13:00:00','0','',NULL,'1',NULL,NULL,NULL,NULL);
insert into `tms_teacher` (`id`, `institution_id`, `name`, `gender`, `birth`, `mobile`, `email`, `post_id`, `hired`, `leaved`, `is_leaved`, `note`, `token`, `is_actived`, `logic_deleted`, `created`, `updated`, `user_id`) values('6','1','Smile','2',NULL,NULL,'ddd@gmail.com',NULL,'2021-02-28 13:00:00','2021-02-28 13:00:00','0',NULL,NULL,'1',NULL,NULL,NULL,NULL);
insert into `tms_teacher` (`id`, `institution_id`, `name`, `gender`, `birth`, `mobile`, `email`, `post_id`, `hired`, `leaved`, `is_leaved`, `note`, `token`, `is_actived`, `logic_deleted`, `created`, `updated`, `user_id`) values('7','1','teacher1','1',NULL,'','teacher1@gmail.com',NULL,NULL,NULL,'1','',NULL,'1',NULL,NULL,NULL,NULL);
insert into `tms_teacher` (`id`, `institution_id`, `name`, `gender`, `birth`, `mobile`, `email`, `post_id`, `hired`, `leaved`, `is_leaved`, `note`, `token`, `is_actived`, `logic_deleted`, `created`, `updated`, `user_id`) values('8','1','Hua','1',NULL,'0422223333','Hua@gmail.com',NULL,NULL,NULL,'1','',NULL,'1',NULL,NULL,NULL,NULL);
insert into `tms_teacher` (`id`, `institution_id`, `name`, `gender`, `birth`, `mobile`, `email`, `post_id`, `hired`, `leaved`, `is_leaved`, `note`, `token`, `is_actived`, `logic_deleted`, `created`, `updated`, `user_id`) values('9',NULL,'111','1','2021-03-13','0144442222','yu_xinzhong@163.com',NULL,NULL,NULL,'0','',NULL,'1',NULL,NULL,NULL,NULL);
